ScriptHost:LoadScript("scripts/user_settings.lua")
ScriptHost:LoadScript("scripts/globals.lua")
ScriptHost:LoadScript("scripts/cached_helpers.lua")

ScriptHost:LoadScript("scripts/loading/load_items.lua")
ScriptHost:LoadScript("scripts/loading/load_locations.lua")
ScriptHost:LoadScript("scripts/loading/load_updaters.lua")
ScriptHost:LoadScript("scripts/loading/load_layouts.lua")

ScriptHost:LoadScript("scripts/autotracking/auto_items.lua")
ScriptHost:LoadScript("scripts/autotracking/auto_checks_table.lua")
ScriptHost:LoadScript("scripts/autotracking/auto_checks.lua")
ScriptHost:LoadScript("scripts/autotracking/auto_events.lua")
ScriptHost:LoadScript("scripts/autotracking/auto_skulltulas.lua")
ScriptHost:LoadScript("scripts/autotracking/autotracking.lua")
